dataset_params:
  im_path: 'data/mnist/train/images'
  im_channels : 1
  im_size : 28
  name: 'mnist'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0015
  beta_end : 0.0195

ldm_params:
  down_channels: [ 128, 256, 256, 256]
  mid_channels: [ 256, 256]
  down_sample: [ False, False, False ]
  attn_down : [True, True, True]
  time_emb_dim: 256
  norm_channels : 32
  num_heads : 16
  conv_out_channels : 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  condition_config:
    condition_types: ['class']
    class_condition_config :
      num_classes : 10
      cond_drop_prob : 0.1

train_params:
  seed : 1111
  task_name: 'mnist'
  ldm_batch_size: 16
  disc_start: 1000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  ldm_epochs : 100
  num_samples : 25
  num_grid_rows : 5
  ldm_lr: 0.00001
  save_latents : False
  cf_guidance_scale : 1.0
  ldm_ckpt_name: 'checkpoint/ddpm_ckpt_class_cond.pth'
